# Write your MySQL query statement below
SELECT MACHINE_ID, ROUND(AVG(END_TIME-START_TIME),3) AS PROCESSING_TIME
FROM (
    SELECT MACHINE_ID,PROCESS_ID, MAX(CASE WHEN ACTIVITY_TYPE='END' THEN TIMESTAMP END) AS END_TIME, MAX(CASE WHEN ACTIVITY_TYPE='START' THEN TIMESTAMP END) AS START_TIME

    FROM ACTIVITY
GROUP BY MACHINE_ID, PROCESS_ID
) AS PROCESS
GROUP BY MACHINE_ID;
