# Write your MySQL query statement below
SELECT S.USER_ID, ROUND(IFNULL(SUM(CASE WHEN C.ACTION='CONFIRMED' THEN 1 ELSE 0 END)/NULLIF(COUNT(C.USER_ID),0),0),2) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C
ON S.USER_ID=C.USER_ID
GROUP BY S.USER_ID;