# Write your MySQL query statement below
SELECT ROUND(100*SUM(ORDER_DATE=customer_pref_delivery_date)/COUNT(*),2) AS IMMEDIATE_PERCENTAGE
FROM DELIVERY
WHERE (CUSTOMER_ID, ORDER_DATE) IN (
    SELECT CUSTOMER_ID, MIN(ORDER_DATE)
    FROM DELIVERY
    GROUP BY CUSTOMER_ID
);