# Write your MySQL query statement below
SELECT R.CONTEST_ID, ROUND(COUNT(R.USER_ID)*100.00/(SELECT COUNT(*) FROM USERS),2) AS PERCENTAGE
FROM REGISTER R
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, R.CONTEST_ID ASC;
