# Write your MySQL query statement below
SELECT S.STUDENT_ID,S.STUDENT_NAME,SB.SUBJECT_NAME,COUNT(E.STUDENT_ID) AS ATTENDED_EXAMS
FROM STUDENTS AS S
CROSS JOIN SUBJECTS AS SB
LEFT JOIN  EXAMINATIONS AS E
ON S.STUDENT_ID=E.STUDENT_ID AND SB.SUBJECT_NAME=E.SUBJECT_NAME
GROUP BY s.student_id, s.student_name, sb.subject_name
ORDER BY s.student_id, sb.subject_name;